name: SonarQube Scan (.NET Backend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    name: Build and Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Restore dependencies
      run: dotnet restore eShopOnWeb.sln

    - name: Begin SonarQube scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /k:"eshoponweb" \
          /s:"eShopOnWeb.sln" \
          /d:sonar.login="${SONAR_TOKEN}" \
          /d:sonar.host.url="http://13.89.226.182:9000"

    - name: Build project
      run: dotnet build eShopOnWeb.sln --no-restore --configuration Release

    - name: End SonarQube scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login="${SONAR_TOKEN}"
